import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'], // Các ký tự hỗ trợ
  weight: ['400', '500', '700'], // Độ đậm của font
  variable: '--font-inter', // Tạo biến CSS để sử dụng
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
